In [1]:
import pandas as pd

In [2]:
import numpy as np

In [8]:
labels= ['a','b','c','d']
my_data = [1,2,3,4]
arr = np.array(my_data)
d={'a':1,'b':2,'c':3,'d':4}

In [9]:
pd.Series(data= my_data)

0    1
1    2
2    3
3    4
dtype: int64

In [10]:
pd.Series(data=my_data, index= labels)

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
pd.Series(my_data,labels)

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
pd.Series(arr)

0    1
1    2
2    3
3    4
dtype: int64

In [13]:
pd.Series(d)

a    1
b    2
c    3
d    4
dtype: int64

In [14]:
pd.Series(labels)

0    a
1    b
2    c
3    d
dtype: str

In [15]:
ser1 = pd.Series([1,2,3,4],['USA','PAK','GEM','AFG'])

In [16]:
ser1

USA    1
PAK    2
GEM    3
AFG    4
dtype: int64

In [22]:
ser2 = pd.Series([1,5,3,4],['Canda','PAK','GEM','AFG'])

In [23]:
ser1+ser2

AFG      8.0
Canda    NaN
GEM      6.0
PAK      7.0
USA      NaN
dtype: float64

In [4]:
##Data Frames

In [19]:
from numpy.random import rand

In [22]:
np.random.seed(101)

In [130]:
df = pd.DataFrame(rand(5,4)*4-1,['A','B','C','D','E'],['W','X','Y','Z'])

In [131]:
df

          W         X         Y         Z
A  1.065595  1.282670 -0.886103 -0.313913
B  1.741108  2.335587  0.227865  2.574452
C  1.886175 -0.240244  1.216910  0.408528
D -0.272430  2.142407  2.861933 -0.070585
E -0.665754  1.414194  1.915971  0.104955

In [21]:
df['W']

A    0.324608
B    0.812266
C    0.656595
D    0.748520
E    0.695078
Name: W, dtype: float64

In [22]:
df['W']['A']

np.float64(0.324607996437537)

In [23]:
type(df['W'])

pandas.core.series.Series

In [24]:
type(df)

pandas.core.frame.DataFrame

In [25]:
df.W

A    0.324608
B    0.812266
C    0.656595
D    0.748520
E    0.695078
Name: W, dtype: float64

In [26]:
#Multiple Columns
df[['W','Z']]

          W         Z
A  0.324608  0.637659
B  0.812266  0.424569
C  0.656595  0.529623
D  0.748520  0.687242
E  0.695078  0.203528

In [27]:
df['new'] = df['W']+df['Y']

In [28]:
df

          W         X         Y         Z       new
A  0.324608  0.117578  0.051101  0.637659  0.375709
B  0.812266  0.670260  0.651768  0.424569  1.464034
C  0.656595  0.209161  0.659925  0.529623  1.316520
D  0.748520  0.093757  0.784522  0.687242  1.533042
E  0.695078  0.496867  0.975361  0.203528  1.670440

In [32]:
df.drop('new',axis=1,inplace=True)

In [33]:
df

          W         X         Y         Z
A  0.324608  0.117578  0.051101  0.637659
B  0.812266  0.670260  0.651768  0.424569
C  0.656595  0.209161  0.659925  0.529623
D  0.748520  0.093757  0.784522  0.687242
E  0.695078  0.496867  0.975361  0.203528

In [36]:
df.drop('E',axis=0,inplace=True)

In [37]:
df

          W         X         Y         Z
A  0.324608  0.117578  0.051101  0.637659
B  0.812266  0.670260  0.651768  0.424569
C  0.656595  0.209161  0.659925  0.529623
D  0.748520  0.093757  0.784522  0.687242

In [38]:
df.loc['C']

W    0.656595
X    0.209161
Y    0.659925
Z    0.529623
Name: C, dtype: float64

In [39]:
df.iloc[2]

W    0.656595
X    0.209161
Y    0.659925
Z    0.529623
Name: C, dtype: float64

In [40]:
df.loc['C','Z']

np.float64(0.5296233987530145)

In [42]:
df.loc[['C','C'],['W','Z']]

          W         Z
C  0.656595  0.529623
C  0.656595  0.529623

In [76]:
#Conditional 
df

          W         X         Y         Z
A  1.065595  1.282670 -0.886103 -0.313913
B  1.741108  2.335587  0.227865  2.574452
C  1.886175 -0.240244  1.216910  0.408528
D -0.272430  2.142407  2.861933 -0.070585
E -0.665754  1.414194  1.915971  0.104955

In [77]:
df>0

       W      X      Y      Z
A   True   True  False  False
B   True   True   True   True
C   True  False   True   True
D  False   True   True  False
E  False   True   True   True

In [78]:
booldf = df>0

In [79]:
df[booldf]

          W         X         Y         Z
A  1.065595  1.282670       NaN       NaN
B  1.741108  2.335587  0.227865  2.574452
C  1.886175       NaN  1.216910  0.408528
D       NaN  2.142407  2.861933       NaN
E       NaN  1.414194  1.915971  0.104955

In [80]:
df['W']>0

A     True
B     True
C     True
D    False
E    False
Name: W, dtype: bool

In [81]:
df[df['W']>0]

          W         X         Y         Z
A  1.065595  1.282670 -0.886103 -0.313913
B  1.741108  2.335587  0.227865  2.574452
C  1.886175 -0.240244  1.216910  0.408528

In [83]:
df[df['Z']>0]

          W         X         Y         Z
B  1.741108  2.335587  0.227865  2.574452
C  1.886175 -0.240244  1.216910  0.408528
E -0.665754  1.414194  1.915971  0.104955

In [86]:
df[df['W']>0]['X']

A    1.282670
B    2.335587
C   -0.240244
Name: X, dtype: float64

In [87]:
boolser = df['W']>0

In [88]:
boolser

A     True
B     True
C     True
D    False
E    False
Name: W, dtype: bool

In [89]:
result = df[boolser]

In [90]:
result

          W         X         Y         Z
A  1.065595  1.282670 -0.886103 -0.313913
B  1.741108  2.335587  0.227865  2.574452
C  1.886175 -0.240244  1.216910  0.408528

In [91]:
mycol= ['X','Z']

In [92]:
result[mycol]

          X         Z
A  1.282670 -0.313913
B  2.335587  2.574452
C -0.240244  0.408528

In [93]:
df[df['W']>0][['X','Z']]

          X         Z
A  1.282670 -0.313913
B  2.335587  2.574452
C -0.240244  0.408528

In [132]:
df[(df['W']>0) & (df['Y']>1)]

          W         X        Y         Z
C  1.886175 -0.240244  1.21691  0.408528

In [133]:
df.reset_index()

  index         W         X         Y         Z
0     A  1.065595  1.282670 -0.886103 -0.313913
1     B  1.741108  2.335587  0.227865  2.574452
2     C  1.886175 -0.240244  1.216910  0.408528
3     D -0.272430  2.142407  2.861933 -0.070585
4     E -0.665754  1.414194  1.915971  0.104955

In [136]:
df['State']  = ['Aaa','Bbb','cccc','eeee','fff']

In [137]:
df

          W         X         Y         Z State
A  1.065595  1.282670 -0.886103 -0.313913   Aaa
B  1.741108  2.335587  0.227865  2.574452   Bbb
C  1.886175 -0.240244  1.216910  0.408528  cccc
D -0.272430  2.142407  2.861933 -0.070585  eeee
E -0.665754  1.414194  1.915971  0.104955   fff

In [138]:
df.set_index('State')

              W         X         Y         Z
State
Aaa    1.065595  1.282670 -0.886103 -0.313913
Bbb    1.741108  2.335587  0.227865  2.574452
cccc   1.886175 -0.240244  1.216910  0.408528
eeee  -0.272430  2.142407  2.861933 -0.070585
fff   -0.665754  1.414194  1.915971  0.104955

In [15]:
#index Level
outside = ['G1','G1','G1','G2','G2','G2']
inside =[1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [16]:
pd.MultiIndex.from_tuples(hier_index)

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [29]:
df = pd.DataFrame(
    {'A':[10,20,30,40,50,60],'B': [80,90,100,120,130,140]},
    index=[outside, inside]
)

In [30]:
df

       A    B
G1 1  10   80
   2  20   90
   3  30  100
G2 1  40  120
   2  50  130
   3  60  140

In [31]:
df.loc['G1']

    A    B
1  10   80
2  20   90
3  30  100

In [37]:
df.loc['G1']

    A    B
1  10   80
2  20   90
3  30  100

In [40]:
df.loc['G1'].loc[1]

A    10
B    80
Name: 1, dtype: int64

In [44]:
print(df.index.names)

[None, None]

In [47]:
df.index.names = ['Group','Num']

In [48]:
df

            A    B
Group Num
G1    1    10   80
      2    20   90
      3    30  100
G2    1    40  120
      2    50  130
      3    60  140

In [49]:
df.loc['G2'].loc[3].loc['A']

np.int64(60)

In [50]:
df.loc['G1'].loc[3].loc['B']

np.int64(100)

In [51]:
df.xs(2,level='Num')

        A    B
Group
G1     20   90
G2     50  130