In [2]:
import pandas as pd

In [3]:
import numpy as np

In [8]:
labels= ['a','b','c','d']
my_data = [1,2,3,4]
arr = np.array(my_data)
d={'a':1,'b':2,'c':3,'d':4}

In [9]:
pd.Series(data= my_data)

0    1
1    2
2    3
3    4
dtype: int64

In [10]:
pd.Series(data=my_data, index= labels)

a    1
b    2
c    3
d    4
dtype: int64

In [11]:
pd.Series(my_data,labels)

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
pd.Series(arr)

0    1
1    2
2    3
3    4
dtype: int64

In [13]:
pd.Series(d)

a    1
b    2
c    3
d    4
dtype: int64

In [14]:
pd.Series(labels)

0    a
1    b
2    c
3    d
dtype: str

In [15]:
ser1 = pd.Series([1,2,3,4],['USA','PAK','GEM','AFG'])

In [16]:
ser1

USA    1
PAK    2
GEM    3
AFG    4
dtype: int64

In [22]:
ser2 = pd.Series([1,5,3,4],['Canda','PAK','GEM','AFG'])

In [23]:
ser1+ser2

AFG      8.0
Canda    NaN
GEM      6.0
PAK      7.0
USA      NaN
dtype: float64

In [4]:
##Data Frames

In [10]:
from numpy.random import rand

In [11]:
np.random.seed(101)

In [19]:
df = pd.DataFrame(rand(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [20]:
df

          W         X         Y         Z
A  0.324608  0.117578  0.051101  0.637659
B  0.812266  0.670260  0.651768  0.424569
C  0.656595  0.209161  0.659925  0.529623
D  0.748520  0.093757  0.784522  0.687242
E  0.695078  0.496867  0.975361  0.203528

In [21]:
df['W']

A    0.324608
B    0.812266
C    0.656595
D    0.748520
E    0.695078
Name: W, dtype: float64

In [22]:
df['W']['A']

np.float64(0.324607996437537)

In [23]:
type(df['W'])

pandas.core.series.Series

In [24]:
type(df)

pandas.core.frame.DataFrame

In [25]:
df.W

A    0.324608
B    0.812266
C    0.656595
D    0.748520
E    0.695078
Name: W, dtype: float64

In [26]:
#Multiple Columns
df[['W','Z']]

          W         Z
A  0.324608  0.637659
B  0.812266  0.424569
C  0.656595  0.529623
D  0.748520  0.687242
E  0.695078  0.203528

In [27]:
df['new'] = df['W']+df['Y']

In [28]:
df

          W         X         Y         Z       new
A  0.324608  0.117578  0.051101  0.637659  0.375709
B  0.812266  0.670260  0.651768  0.424569  1.464034
C  0.656595  0.209161  0.659925  0.529623  1.316520
D  0.748520  0.093757  0.784522  0.687242  1.533042
E  0.695078  0.496867  0.975361  0.203528  1.670440

In [32]:
df.drop('new',axis=1,inplace=True)

In [33]:
df

          W         X         Y         Z
A  0.324608  0.117578  0.051101  0.637659
B  0.812266  0.670260  0.651768  0.424569
C  0.656595  0.209161  0.659925  0.529623
D  0.748520  0.093757  0.784522  0.687242
E  0.695078  0.496867  0.975361  0.203528

In [36]:
df.drop('E',axis=0,inplace=True)

In [37]:
df

          W         X         Y         Z
A  0.324608  0.117578  0.051101  0.637659
B  0.812266  0.670260  0.651768  0.424569
C  0.656595  0.209161  0.659925  0.529623
D  0.748520  0.093757  0.784522  0.687242

In [38]:
df.loc['C']

W    0.656595
X    0.209161
Y    0.659925
Z    0.529623
Name: C, dtype: float64

In [39]:
df.iloc[2]

W    0.656595
X    0.209161
Y    0.659925
Z    0.529623
Name: C, dtype: float64

In [40]:
df.loc['C','Z']

np.float64(0.5296233987530145)

In [42]:
df.loc[['C','C'],['W','Z']]

          W         Z
C  0.656595  0.529623
C  0.656595  0.529623